# TensorFlow 2 - Basics

In [54]:
import tensorflow as tf

print(f"TensorFlow version: {tf.__version__}")

gpus = tf.config.list_physical_devices('GPU')
print(gpus)

TensorFlow version: 2.17.0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


---

### 1. Create a `tensor` with a value of `4`.

In [55]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


---

### 2. Create a `tensor` with a value of `4`, a shape of `1 x 1` and of type `float32`.

In [56]:
x = tf.constant(4, shape=(1, 1), dtype='float32')
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


---

### 3. Create a `tensor` of the shape `2 x 3` with all elements being `0`.

In [57]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


---

### 4. Create a `tensor` of the shape `4 x 5` with all elements being `1` and of type `int32`.

In [58]:
x = tf.ones((4, 5), dtype='int32')
print(x)

tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]], shape=(4, 5), dtype=int32)


---

### 5. Create a `tensor` with an identity matrix of shape `3 x 3`.

In [59]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


---

### 7. Create a `tensor` from normal distribution with mean 0 and standard deviation 2, and with a shape `2 x 3`.

In [60]:
x = tf.random.normal(shape=(2, 3), mean=0, stddev=2)
print(x)

tf.Tensor(
[[ 2.330355   -1.4780736  -0.73033744]
 [-0.5609873  -0.33256018 -2.8336856 ]], shape=(2, 3), dtype=float32)


---

### 8. Create a `tensor` using uniform distribution with minimum value of 1 and maximum value of 2, and with a shape `2 x 2`.

In [61]:
x = tf.random.uniform(shape=(2, 2), minval=1, maxval=2)
print(x)

tf.Tensor(
[[1.329876  1.2366012]
 [1.2304696 1.323716 ]], shape=(2, 2), dtype=float32)


---

### 9. Create a `tensor` of series of integers from 0 through 9 (both inclusive).

In [62]:
x = tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


---

### 10. Create a `tensor` of series of integers from 0 through 9 with a step of 2.

In [63]:
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


---

### 11. Convert the above `tensor` from `int32` to `float32`.

In [64]:
x = tf.cast(x, dtype='float32')
print(x)

tf.Tensor([0. 2. 4. 6. 8.], shape=(5,), dtype=float32)


---

### 12. Perform element-wise addition on `[1, 2, 3]` and `[9, 8, 7]` and print the result.

In [65]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
z = x + y # short-hand for tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


---

### 13. Perform element-wise subtraction on `[1, 2, 3]` and `[9, 8, 7]` and print the result.

In [66]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
z = x - y # short-hand for tf.subtract(x, y)
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


---

### 14. Perform element-wise multiplication on `[1, 2, 3]` and `[11, 22, 33]` and print the result.

In [67]:
x = tf.constant([1, 2, 3])
y = tf.constant([11, 22, 33])
z = x * y # short-hand for tf.multiply(x, y)
print(z)

tf.Tensor([11 44 99], shape=(3,), dtype=int32)


---

### 15. Perform element-wise division on `[10, 20, 30]` and `[1, 2, 3]` and print the result.

In [68]:
x = tf.constant([10, 20, 30])
y = tf.constant([1, 2, 3])
z = x / y # short-hand for tf.divide(x, y)
print(z)

tf.Tensor([10. 10. 10.], shape=(3,), dtype=float64)


---

### 16. Perform dot-product on `[1, 2, 3]` and `[4, 5, 6]` and print the result.

In [69]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


---

### 17. Create a `2 x 2 tensor` and raise each element to the power of 3.

In [70]:
x = tf.constant([[1, 2], [3, 4]])
z = x ** 3  # equivalent to tf.pow(x, 3)
print(z)

tf.Tensor(
[[ 1  8]
 [27 64]], shape=(2, 2), dtype=int32)


---

### 18. Raise one `2 x 2 tensor` to the power of another `2 x 2 tensor` (element-wise).

In [71]:
x = tf.constant([[1, 2], [3, 4]])
y = tf.constant([[2, 3], [2, 3]])
z = tf.pow(x, y)
print(z)

tf.Tensor(
[[ 1  8]
 [ 9 64]], shape=(2, 2), dtype=int32)


---

### 19. Perform a matrix multiplication between a `2 x 3 tensor` and `3 x 2 tensor`.

In [72]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], dtype='int32')
y = tf.constant([[1, 2], [3, 4], [5, 6]], dtype='int32')

print(x)
print(y)

z = x @ y # same as tf.matmul(x, y)
print(z)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[22 28]
 [49 64]], shape=(2, 2), dtype=int32)


---

### 20. Select first 3 elements from a 1-D tensor with 5 elements

In [73]:
x = tf.constant([5, 6, 7, 8, 9], dtype=tf.int8)
print(x[:3])

tf.Tensor([5 6 7], shape=(3,), dtype=int8)


---

### 21. Select the first and last element from the above 1-D tensor using another tensor which has the index values

In [74]:
x = tf.constant([5, 6, 7, 8, 9], dtype=tf.int8)

indices = tf.constant([0, len(x) - 1], dtype=tf.int16)

x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([5 9], shape=(2,), dtype=int8)


---

### 22. Select any `2 x 2` tensor from a `3 x 4` tensor

In [75]:
x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=tf.int8)
print(x)

x_subset = x[:2, :2]
print(x_subset)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int8)
tf.Tensor(
[[1 2]
 [5 6]], shape=(2, 2), dtype=int8)


---

### 23. Reshape a 1-D tensor with `9` elements into a 2-D tensor with `3 x 3` elements

In [76]:
x = tf.range(start=1, limit=10)
print(x)

x_reshaped = tf.reshape(x, shape=(3, 3))
print(x_reshaped)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


---

### 24. Transpose a 2-D tensor with `4 x 5` elements

In [77]:
x = tf.range(start=1, limit=21)
x_reshaped = tf.reshape(x, shape=(4, 5))
print(x_reshaped)

x_transposed = tf.transpose(x_reshaped) # perm=[1, 0] => permutation of axes
print(x_transposed)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]], shape=(5, 4), dtype=int32)


---