# TensorFlow 2 Crash Course Solutions

## What is TensorFlow?

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

In [3]:
gpus = tf.config.list_physical_devices('GPU')
if len(gpus) > 0:
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)

## 1. Create a `tensor` with a value of `4`.

In [4]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


## 2. Create a `tensor` with a value of `4`, a shape of `1 x 1` and of type `float32`.

In [5]:
x = tf.constant(4, shape=(1, 1), dtype='float32')
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


## 3. Create a `tensor` of the shape `2 x 3` with all elements being `0`.

In [6]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


## 4. Create a `tensor` of the shape `4 x 5` with all elements being `1` and of type `int32`.

In [7]:
x = tf.ones((4, 5), dtype='int32')
print(x)

tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]], shape=(4, 5), dtype=int32)


## 5. Create a `tensor` with an identity matrix of shape `3 x 3`.

In [8]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


## 7. Create a `tensor` from normal distribution with mean 0 and standard deviation 2, and with a shape `2 x 3`.

In [9]:
x = tf.random.normal(shape=(2, 3), mean=0, stddev=2)
print(x)

tf.Tensor(
[[-0.7790444  -1.5626675  -0.8583208 ]
 [-0.58128965 -0.12633725 -0.06265599]], shape=(2, 3), dtype=float32)


## 8. Create a `tensor` using uniform distribution with minimum value of 1 and maximum value of 2, and with a shape `2 x 2`.

In [10]:
x = tf.random.uniform(shape=(2, 2), minval=1, maxval=2)
print(x)

tf.Tensor(
[[1.8396721 1.6513225]
 [1.475342  1.2907958]], shape=(2, 2), dtype=float32)


## 9. Create a `tensor` of series of integers from 0 through 9 (both inclusive).

In [11]:
x = tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


## 10. Create a `tensor` of series of integers from 0 through 9 with a step of 2.

In [12]:
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


## 11. Convert the above `tensor` from `int32` to `float32`.

In [13]:
x = tf.cast(x, dtype='float32')
print(x)

tf.Tensor([0. 2. 4. 6. 8.], shape=(5,), dtype=float32)


## 12. Perform element-wise addition on `[1, 2, 3]` and `[9, 8, 7]` and print the result.

In [14]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
z = x + y # short-hand for tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


## 13. Perform element-wise subtraction on `[1, 2, 3]` and `[9, 8, 7]` and print the result.

In [15]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
z = x - y # short-hand for tf.subtract(x, y)
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


## 14. Perform element-wise multiplication on `[1, 2, 3]` and `[11, 22, 33]` and print the result.

In [16]:
x = tf.constant([1, 2, 3])
y = tf.constant([11, 22, 33])
z = x * y # short-hand for tf.multiply(x, y)
print(z)

tf.Tensor([11 44 99], shape=(3,), dtype=int32)


## 15. Perform element-wise division on `[10, 20, 30]` and `[1, 2, 3]` and print the result.

In [17]:
x = tf.constant([10, 20, 30])
y = tf.constant([1, 2, 3])
z = x / y # short-hand for tf.divide(x, y)
print(z)

tf.Tensor([10. 10. 10.], shape=(3,), dtype=float64)


## 16. Perform dot-product on `[1, 2, 3]` and `[4, 5, 6]` and print the result.

In [18]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


## 17. Create a `2 x 2 tensor` and raise each element to the power of 3.

In [19]:
x = tf.constant([[1, 2], [3, 4]])
z = x ** 3  # equivalent to tf.pow(x, 3)
print(z)

tf.Tensor(
[[ 1  8]
 [27 64]], shape=(2, 2), dtype=int32)


## 18. Raise one `2 x 2 tensor` to the power of another `2 x 2 tensor` (element-wise).

In [20]:
x = tf.constant([[1, 2], [3, 4]])
y = tf.constant([[2, 3], [2, 3]])
z = tf.pow(x, y)
print(z)

tf.Tensor(
[[ 1  8]
 [ 9 64]], shape=(2, 2), dtype=int32)


## 19. Perform a matrix multiplication between a `2 x 3 tensor` and `3 x 2 tensor`.

In [21]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], dtype='int32')
y = tf.constant([[1, 2], [3, 4], [5, 6]], dtype='int32')

print(x)
print(y)

z = x @ y # same as tf.matmul(x, y)
print(z)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[22 28]
 [49 64]], shape=(2, 2), dtype=int32)
