# TensorFlow 2 Crash Course

## What is TensorFlow?

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

## 1. Create a `tensorflow` constant with a value of `4`. Keep other properties as default.

In [10]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


## 2. Create a `tensorflow` constant with a value of `4`, a shape of `1 x 1` and of type `float32`.

In [11]:
x = tf.constant(4, shape=(1, 1), dtype='float32')
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


## 3. Create a `tensorflow` constant of shape of `2 x 3` with all elements being `0`.

In [13]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


## 4. Create a `tensorflow` constant of shape of `4 x 5` with all elements being `1` and of type `int32`.

In [15]:
x = tf.ones((4, 5), dtype='int32')
print(x)

tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]], shape=(4, 5), dtype=int32)


In [23]:
x = tf.eye(2, batch_shape=[2, 2])
print(x)

tf.Tensor(
[[[[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]]


 [[[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]]], shape=(2, 2, 2, 2), dtype=float32)


In [25]:
tf.__version__

'2.16.1'