# TensorFlow 2 Crash Course

## What is TensorFlow?

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

## 1. Create a `tensor` with a value of `4`.

In [10]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


## 2. Create a `tensor` with a value of `4`, a shape of `1 x 1` and of type `float32`.

In [11]:
x = tf.constant(4, shape=(1, 1), dtype='float32')
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


## 3. Create a `tensor` of the shape `2 x 3` with all elements being `0`.

In [13]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


## 4. Create a `tensor` of the shape `4 x 5` with all elements being `1` and of type `int32`.

In [15]:
x = tf.ones((4, 5), dtype='int32')
print(x)

tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]], shape=(4, 5), dtype=int32)


## 5. Create a `tensor` with an identity matrix of shape `3 x 3`.

In [26]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


## 7. Create a `tensor` from normal distribution with mean 0 and standard deviation 2, and with a shape `2 x 3`.

In [33]:
x = tf.random.normal(shape=(2, 3), mean=0, stddev=2)
print(x)

tf.Tensor(
[[-3.9282312 -1.6649559  1.8724036]
 [ 2.405164   1.4091673 -1.1579672]], shape=(2, 3), dtype=float32)


## 8. Create a `tensor` using uniform distribution with minimum value of 1 and maximum value of 2, and with a shape `2 x 2`.

In [34]:
x = tf.random.uniform(shape=(2, 2), minval=1, maxval=2)
print(x)

tf.Tensor(
[[1.6551262 1.1092666]
 [1.7352537 1.5910536]], shape=(2, 2), dtype=float32)


## 9. Create a `tensor` of series of integers from 0 through 9 (both inclusive).

In [44]:
x = tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


## 10. Create a `tensor` of series of integers from 0 through 9 with a step of 2.

In [46]:
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
